### PR TITLE
Feature: Additional seek options for android

### PR DESCRIPTION
**Pull request by edusperoni**
Add additional Seek options for android

Also fixes a small inconsistency with the `currentTimeUpdatedEvent` event

### CODE REVIEW

**Comment by bradmartin** [comment]
@edusperoni - I don't have time to review this, I know you from your previous plugin work. Are you interested in being added a collaborator so you have permission to help maintain and merge PRs. I'll check on adding to npm also for publishing rights, that part I have no issue with since it's a quick process to publish a release.

Let me know and I'll add you to this repo.

**Comment by rigor789** [comment]
@bradmartin 
> it's a quick process to publish a release.

Just a quick tip - I'm slowly moving my packages to be released with [`semantic-release`](https://github.com/semantic-release/semantic-release) from CI. This makes it even easier to maintain projects, as you can merge PR's from the GH interface and it will automatically release a new version (if needed). 

Repos where I'm already using it:
 * [vue-scrollto](https://github.com/rigor789/vue-scrollto/blob/master/.circleci/config.yml)
 * [nativescript-vue-navigator](https://github.com/nativescript-vue/nativescript-vue-navigator/blob/master/.github/workflows/semantic-release.yml)

Might be a good idea to do the same for some of the @nstudio repos.

I'll very likely implement it for NativeScript-Vue in the near future as well! :)

**Comment by edusperoni** [comment]
@bradmartin Sure thing. I'm using a couple of plugins in an internal project and I'm adding fixes as we run into issues.

@rigor789 sounds really interesting! I'm always a bit resistant to automated publishing due to the possibility of introducing some regressions on poorly tested PRs. Sometimes when I do a refactor or large amount of work related to an issue I like to publish a beta (so actual users can test it without hassle), which I saw is not very supported (https://github.com/semantic-release/semantic-release/issues/97). That said, I think I'd be fine with a manual trigger of some kind.

**Comment by rigor789** [comment]
> @rigor789 sounds really interesting! I'm always a bit resistant to automated publishing due to the possibility of introducing some regressions on poorly tested PRs. Sometimes when I do a refactor or large amount of work related to an issue I like to publish a beta (so actual users can test it without hassle), which I saw is not very supported ([semantic-release/semantic-release#97](https://github.com/semantic-release/semantic-release/issues/97)). That said, I think I'd be fine with a manual trigger of some kind.

For some projects yes! What I plan on doing with NativeScript-Vue is to automatically release a `dev` version (`v2.5.1-dev.11`, `v2.5.1-dev.12`... etc.) on every commit, but manually release stable versions when needed.

**Pull request merged**
